# -*- coding: utf-8 -*-
"""session_2_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5L_fakmnGzAlTSjnF--GJEAkeGnZrD5

# Control Flow Practice: Conditionals and Loops

This notebook contains practice exercises based on Session 2. Complete each exercise by writing your code in the provided cells.

**Instructions:**
- Read each problem carefully
- Write your solution in the code cell below each exercise
- Run your code to test it
- Try to solve the problems on your own before looking at hints

---

## Part 1: Conditional Statements Practice

---

### Exercise 1: Temperature Classifier

Write a program that:
1. Takes a temperature value as input
2. Prints "Cold" if temperature is below 15
3. Prints "Warm" if temperature is between 15 and 25 (inclusive)
4. Prints "Hot" if temperature is above 25

**Hint:** Use `if-elif-else` statements
"""

# Your code here
temperature = 22  # Test with different values
if temperature <15:
    print("Cold")
elif temperature >= 15 and temperature <= 25:
    print("Warm")
else:
    print("Hot")

"""### Exercise 2: Grade Calculator

Write a program that:
1. Takes a student's score (0-100)
2. Assigns a grade based on:
   - A: 90-100
   - B: 80-89
   - C: 70-79
   - D: 60-69
   - F: below 60
3. Prints the grade

**Bonus:** Also print "Excellent!" for A, "Good job!" for B, "Keep trying!" for C or below

"""

# Your code here
score = 85  # Test with different scores
if score >= 90:
    print("A")
elif score >= 80:
    print("B")
elif score >= 70:
    print("C")
elif score >= 60:
    print("D")
else:
    print("F")

"""### Exercise 3: Login System

Create a simple login system that:
1. Has a predefined username and password
2. Takes user input for both username and password
3. Prints "Login successful!" if both match
4. Prints "Invalid username" if username is wrong
5. Prints "Invalid password" if username is correct but password is wrong

**Hint:** Use nested if statements or `and` operator

"""

# Your code here
correct_username = "admin"
correct_password = "python123"

# Get user input and check credentials
username = input("Please enter your username: ")
password = input("Please enter your password: ")
if username == correct_username and password == correct_password:
    print ("Login successful")
elif username != correct_username:
    print ("Invalid username")
else:
    print ("Invalid password")

"""### Exercise 4: Triangle Validator

Write a program that:
1. Takes three side lengths as input
2. Checks if they can form a valid triangle (sum of any two sides must be greater than the third)
3. If valid, also determine if it's:
   - Equilateral (all sides equal)
   - Isosceles (two sides equal)
   - Scalene (all sides different)
4. Print the result

**Hint:** Use multiple conditions with `and`/`or`

"""

# Your code here
side1 = 5
side2 = 5
side3 = 8
if side1 == side2 == side3:
    print("Equilateral")
elif side1 == side2 != side3 or side1 != side2 == side3:
    print("Isosceles")
else:
    print("Scalene")

"""---

## Part 3: For Loops Practice

---

### Exercise 9: Multiplication Table

Write a program that:
1. Takes a number as input
2. Prints its multiplication table from 1 to 10

**Example output for 5:**
```
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
...
5 x 10 = 50
```
"""

# Your code here
number = int(input("Please enter a number: "))
for i in range(1,11):
    print(f"{number} x {i} = {number * i}")

"""### Exercise 10: List Statistics

Given a list of numbers, calculate and print:
1. The sum of all numbers
2. The average
3. The maximum value
4. The minimum value
5. Count of positive numbers
6. Count of negative numbers

**Challenge:** Do this WITHOUT using built-in functions like `sum()`, `max()`, `min()`

"""

# Your code here
numbers = [23, -5, 42, 16, -8, 7, 31, -12, 0, 19]
pstve = ngtve = summation = 0
mx = mn = numbers[0]
for number in numbers:
    if number < 0:
        ngtve += 1
    elif number > 0:
        pstve += 1
    if number < mn:
        mn = number
    if number > mx:
        mx = number
    summation += number
print(summation)
print(summation / len(numbers))
print(mx)
print(mn)
print(pstve)
print(ngtve)

"""### Exercise 11: Fibonacci Sequence

Generate the first N numbers of the Fibonacci sequence, where:
- The first two numbers are 0 and 1
- Each subsequent number is the sum of the previous two

**Example for N=8:**
```
[0, 1, 1, 2, 3, 5, 8, 13]
```

**Hint:** Use a for loop with range and keep track of the last two numbers

"""

n = 10  # Number of Fibonacci numbers to generate

fst = 0
scnd = 1

print(fst)
print(scnd)

for i in range(2, n):
    nxt = fst + scnd
    print(nxt)
    fst = scnd
    scnd = nxt

"""### Exercise 12: Pattern Printing

Print the following pattern using nested loops:
```
*
**
***
****
*****
```

**Bonus 1:** Make it print in reverse (starting with 5 stars)

**Bonus 2:** Create a pyramid pattern:
```
    *
   ***
  *****
 *******
*********
```

"""

rows = 5
for i in range(1, rows + 1):
    for j in range(i):
        print("*", end="")
    print()
for i in range(rows - 1, 0, -1):
    for j in range(i):
        print("*", end="")
    print()

# Bonus: Pyramid pattern
rows = 5

for i in range(1, rows + 1):
    for space in range(rows - i):
        print(" ", end="")
    for star in range(2 * i - 1):
        print("*", end="")
    print()

"""---

## Part 4: Advanced Loop Techniques

---

### Exercise 13: Working with enumerate()

Given a list of student names, print each with their position number:
1. Starting from 1 (not 0)
2. Format: "Position X: Name"

**Hint:** Use `enumerate()` with the `start` parameter
"""

# Your code here
students = ["Ahmed", "Fatima", "Omar", "Zainab", "Youssef"]
for index, student in enumerate(students):
    print(index+1, student)

"""### Exercise 14: Using zip() for Parallel Lists

You have three lists:
- Product names
- Quantities
- Prices per unit

Calculate and print:
1. Each product with its total cost (quantity × price)
2. The grand total of all products

**Hint:** Use `zip()` to iterate through all three lists together

"""

# Your code here
products = ["Laptop", "Mouse", "Keyboard", "Monitor"]
quantities = [2, 5, 3, 1]
prices = [800, 25, 50, 300]
total = 0
for product , quantity , price in zip(products, quantities , prices):
    print(product, quantity * price)
    total += quantity * price
print(total)

"""### Exercise 15: Dictionary Operations

Given a dictionary of student grades:
1. Print all students who scored above 80
2. Calculate the class average
3. Find the student with the highest grade
4. Count how many students passed (grade >= 60)

"""

# Your code here
grades = {
    "Ahmed": 85,
    "Sara": 92,
    "Omar": 78,
    "Layla": 88,
    "Karim": 65,
    "Nour": 95,
    "Hassan": 72
}
avg = 0
mx = grades["Ahmed"]
mx_name = ""
cntr = 0
for index, grade in grades.items():
    if grade > 80:
        print(index)
    avg += grade
    if grade > mx:
        mx_name = index
    if grade >= 60:
        cntr+=1
print(avg/len(grades))
print(mx_name)
print(cntr)

"""### Exercise 16: Building a Dictionary from Lists

You have two lists:
- A list of country names
- A list of their capitals

Create a dictionary where countries are keys and capitals are values, then:
1. Print the complete dictionary
2. Ask the user for a country and print its capital
3. Handle cases where the country is not in the dictionary

"""

# Your code here
countries = ["Egypt", "France", "Japan", "Brazil", "Canada"]
capitals = ["Cairo", "Paris", "Tokyo", "Brasília", "Ottawa"]
dictionary = {}
for country , capital in zip (countries , capitals):
        dictionary[country] = capital
print(dictionary)
country = input("Please enter your country: ")
if country not in dictionary:
    print("Invalid country")
else:
    print(dictionary[country])

"""---

## Part 5: Comprehensive Challenges

These exercises combine multiple concepts from the session.

---

### Challenge 1: Prime Number Checker

Write a program that:
1. Takes a number as input
2. Checks if it's a prime number (only divisible by 1 and itself)
3. Prints "Prime" or "Not Prime"
4. If not prime, also print its factors

**Hint:** A prime number has exactly 2 factors: 1 and itself
"""

# Your code here
number = int(input("Please enter a number: "))
factors = []
checker = False

for i in range(1, number + 1):
    if number % i == 0:
        factors.append(i)

if len(factors) == 2:
    print("Prime")
else:
    print("Not Prime")
    print(factors)

"""### Challenge 2: Student Management System

Create a simple student management system that:
1. Stores student data in a dictionary (name as key, grade as value)
2. Provides a menu with options:
   - Add a student
   - View all students
   - Search for a student
   - Calculate class average
   - Exit
3. Keeps running until the user chooses to exit

**Hint:** Use a while loop with if-elif statements for the menu

"""

students = {}
choice = ""

while choice != "0":
    print("\n1. Add a student")
    print("2. View all students")
    print("3. Search for a student")
    print("4. Calculate class average")
    print("0. Exit")

    choice = input("Please enter your choice: ")

    if choice == "1":
        name = input("Add name of student: ")
        score = float(input("Add score of student: "))
        students[name] = score
    elif choice == "2":
        if students:
            for name, score in students.items():
                print(f"{name}: {score}")
        else:
            print("No students yet.")
    elif choice == "3":
        student = input("Enter student name to search for: ")
        if student in students:
            print(f"{student}: {students[student]}")
        else:
            print("Invalid student")
    elif choice == "4":
        if students:
            average = sum(students.values()) / len(students)
            print("Class average:", average)
        else:
            print("No students to calculate average.")
    elif choice == "0":
        print("Exiting program...")
        break
    else:
        print("Please enter a valid choice")

"""### Challenge 3: Word Frequency Counter

Write a program that:
1. Takes a sentence as input
2. Counts how many times each word appears
3. Stores results in a dictionary
4. Prints words and their frequencies, sorted by frequency (highest first)

**Hint:**
- Use `.lower()` to make it case-insensitive
- Use `.split()` to separate words
- You may need to remove punctuation

"""

# Your code here
sentence = input("Enter a sentence: ")
sentence = sentence.lower()
clean_sentence = ''.join(char for char in sentence if char.isalnum() or char.isspace())
clean_sentence = clean_sentence.split()
word_freq = {}
for word in clean_sentence:
    if word in word_freq:
        word_freq[word] += 1
    else:
        word_freq[word] = 1
sorted(word_freq.items(), key=lambda x: x[1], reverse=True)
print(word_freq)

"""### Challenge 4: Matrix Operations

Given a 2D list (matrix), write programs to:
1. Print the matrix in a formatted way
2. Calculate the sum of each row
3. Calculate the sum of each column
4. Find the maximum value in the entire matrix

**Hint:** Use nested loops

"""

# Your code here
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

for row in matrix:
    print(" ".join(f"{x:3}" for x in row))
for i, row in enumerate(matrix):
    row_sum = sum(row)
    print(row_sum)
num_cols = len(matrix[0])
for col in range(num_cols):
    col_sum = sum(matrix[row][col] for row in range(len(matrix)))
    print(col_sum)
mx = matrix[0][0]
for row in matrix:
    for val in row:
        if val > mx:
            mx = val
print(mx)

"""---

## Congratulations! 🎉

You've completed the Control Flow practice exercises!

### Next Steps:
1. Review any exercises you found challenging
2. Try modifying the exercises with different inputs
3. Create your own variations of these problems
4. Combine concepts to build more complex programs

### Tips for Learning:
- If stuck, break the problem into smaller steps
- Use print statements to debug your code
- Don't be afraid to experiment and make mistakes
- Practice regularly to build your skills

Keep coding! 💻

---

"""